"""Access link management for VBAN-Bridge.

One-time access links are generated by admins and shared with users.
Each link can only be used once and expires after LINK_EXPIRY_MINUTES.
"""
import hashlib
import secrets
from datetime import datetime, timedelta
from typing import Optional, List, Dict
from config import LINK_EXPIRY_MINUTES
from database.db import execute_query, fetch_all, fetch_one


async def generate_access_link(
    created_by_user_id: int,
    expiry_minutes: int = None,
    purpose: str = "login",
    allowed_role: str = "guest",
    max_uses: int = 1,
    per_ip_limit: int = 1,
    per_user_agent_limit: int = 1,
    quota_window_minutes: int = 60,
    is_public: bool = False,
) -> str:
    """Generate a one-time access link token and store in DB."""
    token = secrets.token_urlsafe(32)
    expiry = expiry_minutes or LINK_EXPIRY_MINUTES
    expires_at = (datetime.utcnow() + timedelta(minutes=expiry)).isoformat()
    purpose = (purpose or "login").strip().lower()[:32]
    allowed_role = (allowed_role or "guest").strip().lower()
    max_uses = max(1, int(max_uses or 1))
    per_ip_limit = max(1, int(per_ip_limit or 1))
    per_user_agent_limit = max(1, int(per_user_agent_limit or 1))
    quota_window_minutes = max(1, int(quota_window_minutes or 60))
    is_public_flag = 1 if is_public else 0

    await execute_query(
        "INSERT INTO access_links (token, created_by, expires_at, purpose, allowed_role, max_uses, per_ip_limit, per_user_agent_limit, quota_window_minutes, is_public) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (token, created_by_user_id, expires_at, purpose, allowed_role, max_uses, per_ip_limit, per_user_agent_limit, quota_window_minutes, is_public_flag),
    )
    return token


def fingerprint_user_agent(user_agent: str) -> str:
    """Create a stable browser fingerprint for quota limiting without storing raw user-agent data."""
    if not user_agent:
        return "unknown"
    return hashlib.sha256(user_agent.encode("utf-8")).hexdigest()[:32]


async def validate_and_consume_link(
    token: str,
    purpose: str = None,
    required_role: str = "guest",
    client_ip: str = None,
    user_agent: str = None,
) -> Optional[int]:
    """Validate a one-time access link and enforce purpose, role, and quota rules."""
    link = await fetch_one(
        "SELECT id, is_used, expires_at, purpose, allowed_role, max_uses, used_count, per_ip_limit, per_user_agent_limit, quota_window_minutes FROM access_links WHERE token = ?",
        (token,),
    )

    if not link:
        return None

    if purpose and link["purpose"] and link["purpose"] != purpose:
        return None

    if required_role and link["allowed_role"] and link["allowed_role"] != required_role:
        return None

    if link["is_used"] or link["used_count"] >= int(link["max_uses"]):
        return None

    expires_at = datetime.fromisoformat(link["expires_at"])
    if datetime.utcnow() > expires_at:
        return None

    quota_window_minutes = int(link["quota_window_minutes"] or 60)
    ip_limit = int(link["per_ip_limit"] or 1)
    ua_limit = int(link["per_user_agent_limit"] or 1)
    ua_hash = fingerprint_user_agent(user_agent) if user_agent else None

    if client_ip:
        ip_count = await fetch_one(
            "SELECT COUNT(*) as c FROM access_link_usage WHERE link_id = ? AND ip_address = ? AND used_at >= ?",
            (link["id"], client_ip, (datetime.utcnow() - timedelta(minutes=quota_window_minutes)).isoformat()),
        )
        if int((ip_count or {}).get("c", 0) or 0) >= ip_limit:
            return None

    if ua_hash:
        ua_count = await fetch_one(
            "SELECT COUNT(*) as c FROM access_link_usage WHERE link_id = ? AND user_agent_hash = ? AND used_at >= ?",
            (link["id"], ua_hash, (datetime.utcnow() - timedelta(minutes=quota_window_minutes)).isoformat()),
        )
        if int((ua_count or {}).get("c", 0) or 0) >= ua_limit:
            return None

    await execute_query(
        "UPDATE access_links SET used_count = used_count + 1, is_used = CASE WHEN used_count + 1 >= max_uses THEN 1 ELSE 0 END, used_at = datetime('now') WHERE id = ?",
        (link["id"],),
    )
    await execute_query(
        "INSERT INTO access_link_usage (link_id, ip_address, user_agent_hash, used_at) VALUES (?, ?, ?, datetime('now'))",
        (link["id"], client_ip, ua_hash),
    )

    return link["id"]


async def get_all_links() -> List[Dict]:
    """Get all access links with their status for admin dashboard."""
    rows = await fetch_all(
        """SELECT al.id, al.token, al.is_used, al.created_at, al.used_at, al.expires_at,
                  al.purpose, al.allowed_role, al.max_uses, al.used_count,
                  al.per_ip_limit, al.per_user_agent_limit, al.quota_window_minutes,
                  u.username as created_by_name
           FROM access_links al
           JOIN users u ON al.created_by = u.id
           ORDER BY al.created_at DESC
           LIMIT 100"""
    )
    result = []
    for row in rows:
        expires_at = datetime.fromisoformat(row["expires_at"])
        is_expired = datetime.utcnow() > expires_at
        status = "used" if row["is_used"] else ("expired" if is_expired else "active")
        result.append({
            "id": row["id"],
            "token": row["token"],
            "status": status,
            "purpose": row["purpose"],
            "allowed_role": row["allowed_role"],
            "max_uses": row["max_uses"],
            "used_count": row["used_count"],
            "per_ip_limit": row["per_ip_limit"],
            "per_user_agent_limit": row["per_user_agent_limit"],
            "quota_window_minutes": row["quota_window_minutes"],
            "created_at": row["created_at"],
            "used_at": row["used_at"],
            "expires_at": row["expires_at"],
            "created_by": row["created_by_name"],
        })
    return result


async def revoke_link(link_id: int) -> bool:
    """Revoke an unused access link."""
    await execute_query(
        "DELETE FROM access_links WHERE id = ? AND is_used = 0",
        (link_id,),
    )
    return True
