"""Access link management for VBAN-Bridge.

One-time access links are generated by admins and shared with users.
Each link can only be used once and expires after LINK_EXPIRY_MINUTES.
"""
import hashlib
import secrets
from datetime import datetime, timedelta
from typing import Optional, List, Dict
from config import LINK_EXPIRY_MINUTES
from database.db import execute_query, fetch_all, fetch_one


async def generate_access_link(
    created_by_user_id: int,
    expiry_minutes: int = None,
    purpose: str = "login",
    allowed_role: str = "guest",
    max_uses: int = 1,
    per_ip_limit: int = 1,
    per_user_agent_limit: int = 1,
    per_user_limit: int = 1,
    quota_window_minutes: int = 60,
    cooldown_minutes: int = 0,
    max_uploads_per_window: int = 1,
    upload_window_minutes: int = 60,
    is_public: bool = False,
) -> str:
    """Generate an access link token and store its policy in DB."""
    token = secrets.token_urlsafe(32)
    expiry = expiry_minutes or LINK_EXPIRY_MINUTES
    expires_at = (datetime.utcnow() + timedelta(minutes=expiry)).isoformat()
    purpose = (purpose or "login").strip().lower()[:32]
    allowed_role = (allowed_role or "guest").strip().lower()
    max_uses = max(1, int(max_uses or 1))
    per_ip_limit = max(1, int(per_ip_limit or 1))
    per_user_agent_limit = max(1, int(per_user_agent_limit or 1))
    per_user_limit = max(1, int(per_user_limit or 1))
    quota_window_minutes = max(1, int(quota_window_minutes or 60))
    cooldown_minutes = max(0, int(cooldown_minutes or 0))
    max_uploads_per_window = max(1, int(max_uploads_per_window or 1))
    upload_window_minutes = max(1, int(upload_window_minutes or 60))
    is_public_flag = 1 if is_public else 0

    await execute_query(
        "INSERT INTO access_links (token, created_by, expires_at, purpose, allowed_role, max_uses, per_ip_limit, per_user_agent_limit, per_user_limit, quota_window_minutes, cooldown_minutes, max_uploads_per_window, upload_window_minutes, is_public) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (token, created_by_user_id, expires_at, purpose, allowed_role, max_uses, per_ip_limit, per_user_agent_limit, per_user_limit, quota_window_minutes, cooldown_minutes, max_uploads_per_window, upload_window_minutes, is_public_flag),
    )
    return token


async def generate_invite_code(
    created_by_user_id: int,
    code: str = None,
    role: str = "guest",
    expires_minutes: int = 60,
    max_uses: int = 1,
    allow_uploads: bool = True,
    allow_urls: bool = True,
) -> str:
    """Create a reusable access code that grants a role and limited usage."""
    code_value = (code or secrets.token_urlsafe(8)).strip().upper().replace(" ", "-")
    code_value = code_value[:32]
    if not code_value:
        code_value = f"ACCESS-{secrets.token_hex(4).upper()}"

    expires_at = (datetime.utcnow() + timedelta(minutes=max(1, int(expires_minutes or 60)))).isoformat()
    role_name = (role or "guest").strip().lower()
    max_uses = max(1, int(max_uses or 1))

    await execute_query(
        "INSERT INTO invite_codes (code, created_by, role, expires_at, max_uses, allow_uploads, allow_urls, is_active) VALUES (?, ?, ?, ?, ?, ?, ?, 1)",
        (code_value, created_by_user_id, role_name, expires_at, max_uses, 1 if allow_uploads else 0, 1 if allow_urls else 0),
    )
    return code_value


async def validate_invite_code(
    code: str,
    required_role: str = "guest",
    client_ip: str = None,
    user_agent: str = None,
) -> Optional[Dict]:
    """Validate a generated invite code and enforce expiry and usage limits."""
    if not code:
        return None

    row = await fetch_one(
        "SELECT id, code, role, expires_at, max_uses, used_count, allow_uploads, allow_urls, is_active FROM invite_codes WHERE code = ?",
        (str(code).strip().upper(),),
    )
    if not row or int(row["is_active"] or 0) != 1:
        return None
    if required_role and row["role"] and row["role"] != required_role:
        return None
    if datetime.utcnow() > datetime.fromisoformat(row["expires_at"]):
        return None
    if int(row["used_count"] or 0) >= int(row["max_uses"] or 1):
        return None

    await execute_query(
        "UPDATE invite_codes SET used_count = used_count + 1 WHERE id = ?",
        (row["id"],),
    )

    return {
        "id": row["id"],
        "code": row["code"],
        "role": row["role"],
        "allow_uploads": bool(int(row["allow_uploads"] or 0)),
        "allow_urls": bool(int(row["allow_urls"] or 0)),
        "used_count": int(row["used_count"] or 0) + 1,
    }


def fingerprint_user_agent(user_agent: str) -> str:
    """Create a stable browser fingerprint for quota limiting without storing raw user-agent data."""
    if not user_agent:
        return "unknown"
    return hashlib.sha256(user_agent.encode("utf-8")).hexdigest()[:32]


async def validate_and_consume_link(
    token: str,
    purpose: str = None,
    required_role: str = "guest",
    client_ip: str = None,
    user_agent: str = None,
) -> Optional[int]:
    """Validate a one-time access link and enforce purpose, role, and quota rules."""
    link = await fetch_one(
        "SELECT id, is_used, expires_at, purpose, allowed_role, max_uses, used_count, per_ip_limit, per_user_agent_limit, per_user_limit, quota_window_minutes, cooldown_minutes, max_uploads_per_window, upload_window_minutes FROM access_links WHERE token = ?",
        (token,),
    )

    if not link:
        return None

    if purpose and link["purpose"] and link["purpose"] != purpose:
        return None

    if required_role and link["allowed_role"] and link["allowed_role"] != required_role:
        return None

    if link["is_used"] or link["used_count"] >= int(link["max_uses"]):
        return None

    expires_at = datetime.fromisoformat(link["expires_at"])
    if datetime.utcnow() > expires_at:
        return None

    quota_window_minutes = int(link["quota_window_minutes"] or 60)
    ip_limit = int(link["per_ip_limit"] or 1)
    ua_limit = int(link["per_user_agent_limit"] or 1)
    ua_hash = fingerprint_user_agent(user_agent) if user_agent else None

    if client_ip:
        ip_count = await fetch_one(
            "SELECT COUNT(*) as c FROM access_link_usage WHERE link_id = ? AND ip_address = ? AND used_at >= ?",
            (link["id"], client_ip, (datetime.utcnow() - timedelta(minutes=quota_window_minutes)).isoformat()),
        )
        if int((ip_count or {}).get("c", 0) or 0) >= ip_limit:
            return None

    if ua_hash:
        ua_count = await fetch_one(
            "SELECT COUNT(*) as c FROM access_link_usage WHERE link_id = ? AND user_agent_hash = ? AND used_at >= ?",
            (link["id"], ua_hash, (datetime.utcnow() - timedelta(minutes=quota_window_minutes)).isoformat()),
        )
        if int((ua_count or {}).get("c", 0) or 0) >= ua_limit:
            return None

    await execute_query(
        "UPDATE access_links SET used_count = used_count + 1, is_used = CASE WHEN used_count + 1 >= max_uses THEN 1 ELSE 0 END, used_at = datetime('now') WHERE id = ?",
        (link["id"],),
    )
    await execute_query(
        "INSERT INTO access_link_usage (link_id, ip_address, user_agent_hash, used_at) VALUES (?, ?, ?, datetime('now'))",
        (link["id"], client_ip, ua_hash),
    )

    return link["id"]


async def can_user_upload_for_link(user_id: int, link_id: int) -> tuple[bool, str]:
    """Return (can_upload, reason). Enforces per-user limits and cooldown policy for an upload link."""
    if not user_id or not link_id:
        return False, "No upload link attached to this account."

    link = await fetch_one(
        "SELECT id, purpose, expires_at, max_uses, used_count, per_user_limit, cooldown_minutes, max_uploads_per_window, upload_window_minutes FROM access_links WHERE id = ?",
        (link_id,),
    )
    if not link:
        return False, "Upload link not found."

    if link["purpose"] != "upload":
        return False, "This link is not configured for uploads."

    expires_at = datetime.fromisoformat(link["expires_at"])
    if datetime.utcnow() > expires_at:
        return False, "This upload link has expired."

    if int(link["used_count"] or 0) >= int(link["max_uses"] or 1):
        return False, "This link has reached its total usage limit."

    per_user_limit = int(link["per_user_limit"] or 1)
    if per_user_limit > 0:
        user_upload_count = await fetch_one(
            "SELECT COUNT(*) as c FROM music_requests WHERE user_id = ? AND source_type = 'upload' AND created_at >= datetime('now', '-' || ? || ' minutes')",
            (user_id, int(link["upload_window_minutes"] or 60)),
        )
        if int((user_upload_count or {}).get("c", 0) or 0) >= per_user_limit:
            return False, "This user has reached the maximum uploads allowed by this link."

    if int(link["cooldown_minutes"] or 0) > 0:
        recent_upload = await fetch_one(
            "SELECT created_at FROM music_requests WHERE user_id = ? AND source_type = 'upload' ORDER BY created_at DESC LIMIT 1",
            (user_id,),
        )
        if recent_upload and recent_upload["created_at"]:
            last_upload = datetime.fromisoformat(recent_upload["created_at"])
            if datetime.utcnow() - last_upload < timedelta(minutes=int(link["cooldown_minutes"])):
                return False, f"You can upload again in {int(link['cooldown_minutes'])} minutes."

    upload_window_minutes = int(link["upload_window_minutes"] or 60)
    max_uploads_per_window = int(link["max_uploads_per_window"] or 1)
    if max_uploads_per_window > 0:
        recent_window_count = await fetch_one(
            "SELECT COUNT(*) as c FROM music_requests WHERE user_id = ? AND source_type = 'upload' AND created_at >= datetime('now', '-' || ? || ' minutes')",
            (user_id, upload_window_minutes),
        )
        if int((recent_window_count or {}).get("c", 0) or 0) >= max_uploads_per_window:
            return False, f"You have reached the upload limit for this window ({max_uploads_per_window} in {upload_window_minutes} minutes)."

    return True, ""


async def get_all_links() -> List[Dict]:
    """Get all access links with their status for admin dashboard."""
    rows = await fetch_all(
        """SELECT al.id, al.token, al.is_used, al.created_at, al.used_at, al.expires_at,
                  al.purpose, al.allowed_role, al.max_uses, al.used_count,
                  al.per_ip_limit, al.per_user_agent_limit, al.per_user_limit,
                  al.quota_window_minutes, al.cooldown_minutes,
                  al.max_uploads_per_window, al.upload_window_minutes,
                  u.username as created_by_name
           FROM access_links al
           JOIN users u ON al.created_by = u.id
           ORDER BY al.created_at DESC
           LIMIT 100"""
    )
    result = []
    for row in rows:
        expires_at = datetime.fromisoformat(row["expires_at"])
        is_expired = datetime.utcnow() > expires_at
        status = "used" if row["is_used"] else ("expired" if is_expired else "active")
        result.append({
            "id": row["id"],
            "token": row["token"],
            "status": status,
            "purpose": row["purpose"],
            "allowed_role": row["allowed_role"],
            "max_uses": row["max_uses"],
            "used_count": row["used_count"],
            "per_ip_limit": row["per_ip_limit"],
            "per_user_agent_limit": row["per_user_agent_limit"],
            "per_user_limit": row["per_user_limit"],
            "quota_window_minutes": row["quota_window_minutes"],
            "cooldown_minutes": row["cooldown_minutes"],
            "max_uploads_per_window": row["max_uploads_per_window"],
            "upload_window_minutes": row["upload_window_minutes"],
            "created_at": row["created_at"],
            "used_at": row["used_at"],
            "expires_at": row["expires_at"],
            "created_by": row["created_by_name"],
        })
    return result


async def revoke_link(link_id: int) -> bool:
    """Revoke an unused access link."""
    await execute_query(
        "DELETE FROM access_links WHERE id = ? AND is_used = 0",
        (link_id,),
    )
    return True


async def get_ban_status(user_id: int = None, ip_address: str = None) -> Optional[Dict]:
    """Return active ban info if the user or IP is currently banned."""
    if user_id:
        row = await fetch_one(
            "SELECT id, user_id, ip_address, reason, banned_until, is_active FROM user_bans WHERE user_id = ? AND is_active = 1 AND (banned_until IS NULL OR datetime(banned_until) > datetime('now')) ORDER BY created_at DESC LIMIT 1",
            (user_id,),
        )
        if row:
            return dict(row)
    if ip_address:
        row = await fetch_one(
            "SELECT id, user_id, ip_address, reason, banned_until, is_active FROM user_bans WHERE ip_address = ? AND is_active = 1 AND (banned_until IS NULL OR datetime(banned_until) > datetime('now')) ORDER BY created_at DESC LIMIT 1",
            (ip_address,),
        )
        if row:
            return dict(row)
    return None


async def register_failed_access(user_id: int = None, ip_address: str = None, reason: str = "invalid_access") -> Optional[Dict]:
    """Track repeated bad attempts and automatically ban after a threshold is reached."""
    await execute_query(
        "INSERT INTO access_attempts (user_id, ip_address, reason, created_at) VALUES (?, ?, ?, datetime('now'))",
        (user_id, ip_address, reason),
    )

    window_start = (datetime.utcnow() - timedelta(minutes=10)).isoformat()
    failures = await fetch_one(
        "SELECT COUNT(*) as c FROM access_attempts WHERE (user_id = ? OR ip_address = ?) AND created_at >= ?",
        (user_id, ip_address, window_start),
    )
    if int((failures or {}).get("c", 0) or 0) >= 5:
        await execute_query(
            "INSERT INTO user_bans (user_id, ip_address, reason, banned_until, is_active) VALUES (?, ?, ?, datetime('now', '+30 minutes'), 1)",
            (user_id, ip_address, f"{reason}: too many failed attempts"),
        )
        return {"banned": True, "reason": "Too many failed attempts"}
    return None


async def create_manual_ban(user_id: int = None, ip_address: str = None, reason: str = "manual_ban", minutes: int = 60) -> Dict:
    """Create a user or IP ban for abuse or policy violations."""
    banned_until = (datetime.utcnow() + timedelta(minutes=max(1, minutes))).isoformat()
    ban_id = await execute_query(
        "INSERT INTO user_bans (user_id, ip_address, reason, banned_until, is_active) VALUES (?, ?, ?, ?, 1)",
        (user_id, ip_address, reason, banned_until),
    )
    return {"id": ban_id, "reason": reason, "banned_until": banned_until}
